---
name: Release semantic-release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  semantic-release:
    uses: careem/shared-workflows/.github/workflows/semantic-release.yaml@master
    secrets: inherit
